version: '3'
services:
  server:
    container_name: upwordly-backend-node
    restart: always
    build: .
    ports:
      - 9090:9090
  visualizer:
    image: dockersamples/visualizer
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/sock.:ro
